### ISSUE TITLE
Segmentation Fault in DosBox

### ISSUE THREAD

**Issue by ghost** [rxi/lovedos#6]
Hello,

Just downloaded and tried LoveDOS in DosBox on a 64bit Linux PC, and when I execute LOVE.EXE command with or without a folder name, dosbox crashes. The output of DosBox is as follows:

```
DOSBox version 0.74
Copyright 2002-2010 DOSBox Team, published under GNU GPL.

CONFIG:Loading primary settings from config file /home/bahri/.dosbox/dosbox-0.74.conf
MIXER:Got different values from SDL: freq 44100, blocksize 512
ALSA:Can't subscribe to MIDI port (65:0) nor (17:0)
MIDI:Opened device:none
DOSBox switched to max cycles, because of the setting: cycles=auto. If the game runs too fast try a fixed cycles amount in DOSBox's options.
Segmentation fault (core dumped)
```
Edit: If forgot to mention that I'm using LoveDOS 0.2.1 in DosBox 0.74 on Solus Linux.

**Comment by rxi** [comment]
If DOSBox is segfaulting then this seems it may be an issue with DOSBox -- as I understand it, software ran from inside it should never make it segfault.

You could give [DOSEMU](http://www.dosemu.org/) a try in the mean time.

**Comment by ghost** [comment]
Thanks.
Okay, I'll try with DOSemu and report back.

**Comment by ghost** [comment]
I managed to get it work with dosbox, thanks.
